# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuiviMailles
                                 A QGIS plugin
 Plugin de suivi faune/flore par mailles avec export et import Geopackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-22
        copyright            : (C) 2026 by Lakriouch Ikram - CEN HAUTS-DE-FRANCE
        email                : lakriouchikram@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SuiviMailles class from file SuiviMailles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .suivi_mailles import SuiviMailles
    return SuiviMailles(iface)
